[package]
name = "lottery"
version = "1.0.3"
authors = []

[addresses]
lottery_address = 'b5a8b199938936bb735c089e81dc310a5383ce03035e051f7cfdc98680c50f27'


[dev-addresses]

[dependencies.AptosFramework]
git = "https://github.com/aptos-labs/aptos-core.git"
rev = "testnet"
subdir = "aptos-move/framework/aptos-framework"

[dev-dependencies]
